# Generated by Django 4.1.5 on 2023-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_itemmenu_item_alter_itemmenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='items_list', through='menu_app.ItemMenu', to='menu_app.item'),
        ),
    ]
