# Generated by Django 4.1.5 on 2023-01-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='menu_app.menu', verbose_name='Подменю'),
        ),
    ]
