# Generated by Django 4.1.5 on 2023-01-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_menu_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='submenu',
        ),
        migrations.CreateModel(
            name='MenuSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_1', to='menu_app.menu')),
                ('menu_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_2', to='menu_app.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='submenu',
            field=models.ManyToManyField(related_name='sub_menu', through='menu_app.MenuSub', to='menu_app.menu'),
        ),
    ]
